### ISSUE TITLE
get_pool_prefix error

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#117]
Topology: trying to create loop between 2 ports of same node
```
- type: lan
  bridge: r1-loop
  r1:
- type: lan
  bridge: r1-loop
  r1:
```

Result:
```
jeroen@jvm:~/srlinux/netsim-examples/routing/sr-isis-te$ netlab create
Traceback (most recent call last):
  File "/home/jeroen/srlinux/netsim-tools/netlab", line 8, in <module>
    netsim.cli.lab_commands()
  File "/home/jeroen/srlinux/netsim-tools/netsim/cli/__init__.py", line 78, in lab_commands
    mod.run(sys.argv[arg_start:])   # type: ignore
  File "/home/jeroen/srlinux/netsim-tools/netsim/cli/create.py", line 74, in run
    augment.main.transform(topology)
  File "/home/jeroen/srlinux/netsim-tools/netsim/augment/main.py", line 63, in transform
    transform_data(topology)
  File "/home/jeroen/srlinux/netsim-tools/netsim/augment/main.py", line 48, in transform_data
    augment.links.transform(topology.links,topology.defaults,topology.nodes,topology.pools)
  File "/home/jeroen/srlinux/netsim-tools/netsim/augment/links.py", line 405, in transform
    augment_lan_link(link,pools,nodes,defaults=defaults)
  File "/home/jeroen/srlinux/netsim-tools/netsim/augment/links.py", line 199, in augment_lan_link
    pfx_list = augment_link_prefix(link,['lan'],addr_pools)
  File "/home/jeroen/srlinux/netsim-tools/netsim/augment/links.py", line 185, in augment_link_prefix
    pfx_list = addressing.get(addr_pools,pools)
  File "/home/jeroen/srlinux/netsim-tools/netsim/addressing.py", line 240, in get
    return get_pool_prefix(pools,p,n)
  File "/home/jeroen/srlinux/netsim-tools/netsim/addressing.py", line 231, in get_pool_prefix
    prefixes[af] = next(pools[p][af])
StopIteration
```

**Comment by jbemmel** [comment]
Adding 'prefix: False' solves it, looks like the IP pool runs out

**Comment by ipspace** [comment]
There might be something else wrong with your topology. It might be a good idea to post the whole topology file with bug reports -- I would love to see yours as I'd love to be able to catch that error and cope with it.

This is my whole topology file (and it works). Obviously the two interfaces get IP addresses from different subnets.

```
defaults.device: iosv

nodes: [ r1 ]

links:
- type: lan
  bridge: r1-loop
  r1:
- type: lan
  bridge: r1-loop
  r1:
```

For topologies that go against the current spirit of the tool, it might be best to turn off the IPAM features like you did: set link prefix to False (or use the l2only pool) and use static interface IP (node-on-link) addresses.

**Comment by jbemmel** [comment]
Issue occurs when you include:
```
addressing:
  lan:
    ipv4: 192.168.1.0/24
```

**Comment by ipspace** [comment]
No surprise there -- with the default allocation size of /24, you cannot get more than one prefix out of the pool, but your topology needs two. Will fix the code to do better error reporting.
