### ISSUE TITLE
import resources fails: Python < 3.7

### ISSUE THREAD

**Issue by bbros-dev** [ipspace/netsim-tools#22]
With:
```
$ python --version
Python 3.6.9
```

we observe

```
$ developer/salt0/states/ansible/files/netsim-tools/create-topology 
Traceback (most recent call last):
  File "developer/salt0/states/ansible/files/netsim-tools/create-topology", line 7, in <module>
    import netsim
  File "/home/hedge/src/networkmesh.io/developer/salt0/states/ansible/files/netsim-tools/netsim/__init__.py", line 11, in <module>
    from . import read_topology
  File "/home/hedge/src/networkmesh.io/developer/salt0/states/ansible/files/netsim-tools/netsim/read_topology.py", line 7, in <module>
    from importlib import resources
```

**Comment by ipspace** [comment]
Fixed by #24 and #25
