### ISSUE TITLE
Issues while graphing Static Link Prefixes

### ISSUE THREAD

**Issue by ssasso** [ipspace/netsim-tools#248]
With this topology (from: https://netsim-tools.readthedocs.io/en/latest/example/addressing-tutorial.html#static-link-prefixes):
```
nodes: [ r1, r2 ]
links:
- r1:
  r2:
  prefix: 10.42.42.0/24
```

The *graph* output module is miserably failing with:
```
Traceback (most recent call last):
  File "/usr/local/bin/netlab", line 11, in <module>
    load_entry_point('netsim-tools==1.2.1.dev1', 'console_scripts', 'netlab')()
  File "/usr/local/lib/python3.8/dist-packages/netsim_tools-1.2.1.dev1-py3.8.egg/netsim/cli/__init__.py", line 135, in lab_commands
    mod.run(sys.argv[arg_start:])   # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/netsim_tools-1.2.1.dev1-py3.8.egg/netsim/cli/create.py", line 82, in run
    output_module.write(topology)
  File "/usr/local/lib/python3.8/dist-packages/netsim_tools-1.2.1.dev1-py3.8.egg/netsim/outputs/graph.py", line 175, in write
    if graph_dispatch[output_format](topology,graphfile,self.settings,self.format):
  File "/usr/local/lib/python3.8/dist-packages/netsim_tools-1.2.1.dev1-py3.8.egg/netsim/outputs/graph.py", line 104, in graph_topology
    network_with_label(f,l,settings)
  File "/usr/local/lib/python3.8/dist-packages/netsim_tools-1.2.1.dev1-py3.8.egg/netsim/outputs/graph.py", line 22, in network_with_label
    f.write(' label="%s"' % (n.prefix.ipv4 or n.prefix.ipv6 or n.bridge))
AttributeError: 'str' object has no attribute 'ipv4'
```

Should we add an *if* on *graph.py* to check whether *prefix* is a string or an object?

**Comment by ipspace** [comment]
Nice catch!

We shouldn't overcomplicate output templates, final data structures should be consistent. In this case, **link.prefix** should always be a dictionary of address families. Fixed in d6b15fd.
